### ISSUE TITLE
Local `pre-commit` difficult to use; upgrade to using remote repos

### ISSUE THREAD

**Issue by zwimer** [staticdev/human-readable#694]
It would be a lot easier to use `pre-commit` if it used remote repos instead of `local`. For example:

```yml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
```

Instead of something like:
```yml
repos:
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
        require_serial: true
        args: ["-c", "bandit.yml"]
```
